name: 'pkgcheck'
description: 'Test your package with {pkgcheck}.'
inputs:
  cache-version:
    description: 'Integer to use as cache version. Increment to use new cache.'
    required: true
    default: 1
    
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
    # - name: Set up git user
    #   run: |
    #     git config --local user.name "GitHub Actions"
    #     git config --local user.email "actions@github.com"
    #   shell: bash
    - uses: r-lib/actions/setup-r@v2
    - name: Install c/gtags
      run: |
        sudo apt update
        sudo apt-get install -y global universal-ctags
      shell: bash
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: ${{ inputs.cache_version }}
        extra-packages: |
          local::.
          magrittr
          github::ropensci-review-tools/pkgcheck
    - name: Run pkgcheck
      id: pkgcheck
      run: source("${{ github.action_path }}/check.R")
      shell: Rscript {0}
    - uses: actions/upload-artifact@v2
      with:
        name: visual-network
        path: ${{ steps.pkgcheck.outputs.visnet_path }}
    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: pkgcheck-results.html
